spring.application.name=synchro

spring.profiles.active=test

spring.jpa.open-in-view=true

spring.jpa.hibernate.ddl-auto=create-drop

jwt.public.key.path=D:\\tcc\\keys\\public_key.pem
jwt.private.key.path=D:\\tcc\\keys\\private_key.pem