spring.application.name=synchro

spring.profiles.active=test

spring.jpa.open-in-view=true

spring.jpa.hibernate.ddl-auto=create-drop

spring.jvm.arguments=--enable-native-access=ALL-UNNAMED

jwt.public.key.path=D:\\tcc\\keys\\public_key.pem
jwt.private.key.path=D:\\tcc\\keys\\private_key.pem

lastfm.api-key=7c62ff4c30df11f623f6ecd649c5d104
lastfm.shared-secret=6add1559760f6c27072e36ed5f02cfb4