spring.application.name=synchro

spring.profiles.active=test

spring.jpa.open-in-view=true

spring.jpa.hibernate.ddl-auto=create-drop

spring.jvm.arguments=--enable-native-access=ALL-UNNAMED

jwt.public.key.path=D:\\tcc\\keys\\public_key.pem
jwt.private.key.path=D:\\tcc\\keys\\private_key.pem

lastfm.api-key=69cf991e4eb5a9642175e308ca3cd582
lastfm.shared.secret=be94576ce0d48119843c65b9c6046d0e